### ISSUE TITLE
Distorted text - Landing Page - IE 11

### ISSUE THREAD

**Issue by sharon-ajency** [ajency/Back-to-Basics#10]
Browser: IE 11

Link: http://ajency.in/backtobasic/Portfolio/landing-page.html

Page: Landing Page

Bug: left column layout, the text appears distorted

Description: When clicked on the above link, the two layouts appear the typical layout and the left column layout, the left column layout text appears distorted compared to the typical layout which appears smooth.

![landing-page](https://cloud.githubusercontent.com/assets/10071704/16068098/90b3de8c-32e0-11e6-9faf-f51b026b2e08.png)

**Comment by Valenie** [comment]
This is not an issue. 
The text will appear distorted. 
The images need to be clicked on to view the data.
