### ISSUE TITLE
Image description background not transparent - left column layout - homepage - IE11

### ISSUE THREAD

**Issue by sharon-ajency** [ajency/Back-to-Basics#11]
Browser: IE11 

Page: Left Column Layout Homepage

Link: http://ajency.in/backtobasic/Portfolio/left-column.html#page-top

Issues: The image description background should be transparent, since it covers a part of the image

Description: When clicked on the homepage of the left layout, the background of the image description could be transparent as the image would partially appear, a part of the image gets hidden when opaque.

![left-column html page-top](https://cloud.githubusercontent.com/assets/10071704/16076599/a803b2e8-3311-11e6-8cb6-684578b9c1d4.png)

**Comment by Valenie** [comment]
This is not an issue as the design is done that way.
