### ISSUE TITLE
Text Breaks - Biography - IE11

### ISSUE THREAD

**Issue by sharon-ajency** [ajency/Back-to-Basics#12]
Browser: IE 11

Link: http://ajency.in/backtobasic/Portfolio/left-column.html#service

Page: Biography Page

Bug: 

1.the text gets cut on the right hand side of the page.
2.The year tabs could appear on the same window instead of scrolling downwards

Description: When clicked on the above link, on the page biography, the three headings are shown with the descriptions of each, the fourth heading i.e lectures gets cut. It would be better if only three heading are shown with the descriptions

The year tabs do not appear in the same window , if possible the spacing could be reduced so the whole page appears in a single window

![left-column html service](https://cloud.githubusercontent.com/assets/10071704/16076957/96574256-3313-11e6-8f2b-b12d0d833c05.png)

**Comment by amit0773** [comment]
@sharon-ajency first point is not a bug

**Comment by sharon-ajency** [comment]
Retested Fixed
