### ISSUE TITLE
Quote Symbols - Testimonials Page - IE11

### ISSUE THREAD

**Issue by sharon-ajency** [ajency/Back-to-Basics#14]
Browser: IE11

Page: Testimonials

Link: http://ajency.in/backtobasic/Portfolio/left-column.html#testimonials

Issue: Add quote marks to the testimonials

Description : Quote Marks are missing from the testimonials on the left page layout testimonials page.

![left-column html testimonials](https://cloud.githubusercontent.com/assets/10071704/16077427/5c835562-3316-11e6-8d32-9220c141ae52.png)

**Comment by Valenie** [comment]
This is not an issue as it is already indicated that its a quote by the double inverted commas.
