### ISSUE TITLE
Image description background transparency - Left Layout - Homepage - Mozilla

### ISSUE THREAD

**Issue by sharon-ajency** [ajency/Back-to-Basics#18]
Browser: Mozilla

Page: Left Layout - Homepage 

Link: http://ajency.in/backtobasic/Portfolio/left-column.html#page-top

Issue: The image description background should be transparent, since it covers a part of the image

Description: When clicked on the homepage of the left layout, the background of the image description could be transparent as the image would partially appear, a part of the image gets hidden when opaque.

![left-column html page-top](https://cloud.githubusercontent.com/assets/10071704/16068617/dc9dbd78-32e4-11e6-9ab3-5b05aacf07e0.png)

**Comment by Valenie** [comment]
This is not an issue and designed to be that way.
