### ISSUE TITLE
Text Breaks - Biography - Mozilla

### ISSUE THREAD

**Issue by sharon-ajency** [ajency/Back-to-Basics#19]
Browser: Mozilla

Link: http://ajency.in/backtobasic/Portfolio/left-column.html#service

Page: Biography Page

Bug:

1.the text gets cut on the right hand side of the page.
2.The year tabs could appear on the same window instead of scrolling downwards

Description: When clicked on the above link, on the page biography, the three headings are shown with the descriptions of each, the fourth heading i.e lectures gets cut. It would be better if only three heading are shown with the descriptions

The year tabs do not appear in the same window , if possible the spacing could be reduced so the whole page appears in a single window.

![left-column html service](https://cloud.githubusercontent.com/assets/10071704/16068656/340c1956-32e5-11e6-9397-43e28271f0ca.png)

**Comment by amit0773** [comment]
Issue fixed
