### ISSUE TITLE
Images not uniform - Left Layout - Work Page - Mozilla

### ISSUE THREAD

**Issue by sharon-ajency** [ajency/Back-to-Basics#20]
Browser: Mozilla

Page: Left Layout - Work Page 

Link: http://ajency.in/backtobasic/Portfolio/left-column.html#work

Issue: images could be uniformly arranged so as to prevent large gaps.

Description: When clicked on the above link, as we browse the images under the work section , at the end there is a large gap, either the images need to be positioned in a way as to show uniformity or they need to be resized.

![left-column html work](https://cloud.githubusercontent.com/assets/10071704/16106981/bd7ce0c2-33b6-11e6-8460-065703603230.png)

**Comment by amit0773** [comment]
Invalid issue the layout is in masonry format the image is positioned as per view port

**Comment by sharon-ajency** [comment]
Invalid
