### ISSUE TITLE
Images not uniform - Typical Layout - Work Page - Mozilla

### ISSUE THREAD

**Issue by sharon-ajency** [ajency/Back-to-Basics#22]
Browser: Mozilla

Page:Typical Layout - Work Page

Link: http://ajency.in/backtobasic/Portfolio/typical.html#work

Issue: images could be uniformly arranged so as to prevent large gaps.

Description: When clicked on the above link, as we browse the images under the work section , at the end there is a large gap, either the images need to be positioned in a way as to show uniformity or they need to be resized.

![typical html work](https://cloud.githubusercontent.com/assets/10071704/16107235/a9dafa02-33b8-11e6-827b-192cda5c5bbe.png)

**Comment by amit0773** [comment]
issue fixed
