### ISSUE TITLE
Spacing Issue - Mozilla - Typical Layout - Testimonials

### ISSUE THREAD

**Issue by sharon-ajency** [ajency/Back-to-Basics#23]
Browser: Mozilla

Page: Typical Layout - Testimonials

Link: http://ajency.in/backtobasic/Portfolio/typical.html#testimonials

Issue: Too much of spacing between the quotes and the testimonials

Description: On clicking the above link, as we read the testimonials, there is too much of space left between the quote marks and the customer's testimonial. The space needs to be removed.

![typical html testimonials](https://cloud.githubusercontent.com/assets/10071704/16107298/29ab7c52-33b9-11e6-97b6-670159567413.png)

**Comment by amit0773** [comment]
issue fixed

**Comment by sharon-ajency** [comment]
fixed retested.
