### ISSUE TITLE
Typical Layout - Contact - Mozilla

### ISSUE THREAD

**Issue by sharon-ajency** [ajency/Back-to-Basics#24]
Browser: Mozilla

Page: Typical Layout Contact

Link: http://ajency.in/backtobasic/Portfolio/typical.html#contact

Issue: entire page could be displayed in a single window instead of scrolling down to view the submit button

Description: When clicked on the above link, the entire contact form could be displayed in a single window instead of scrolling down to the submit button. This could be done by removing the extra spacing.

![typical html contact](https://cloud.githubusercontent.com/assets/10071704/16107411/d2fef824-33b9-11e6-86df-f1ec6e61f3ce.png)

**Comment by kapil-ajency** [comment]
Agreed.

**Comment by amit0773** [comment]
issue fixed
