### ISSUE TITLE
Spacing at the beginning of text - Landing Page - MI - Chrome

### ISSUE THREAD

**Issue by sharon-ajency** [ajency/Back-to-Basics#25]
Device: MI

Browser: Chrome

Page: Landing Page

Link: http://ajency.in/backtobasic/Portfolio/landing-page.html

Issues: too much of spacing at the begining of the text

Description: There is a lot of space left above the starting of the text in the landscape and potrait view when clicked on the above link.

Landscape View:

![landing-page landscape](https://cloud.githubusercontent.com/assets/10071704/16114538/6972158c-33df-11e6-98de-d55876ac103d.png)

Potrait View:

![landing-page potrait](https://cloud.githubusercontent.com/assets/10071704/16114539/69869e08-33df-11e6-9df8-37681eea6c40.png)

**Comment by amit0773** [comment]
issue fixed
